In [1]:
print("Hello World!")

Hello World!


In [3]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
import time
a=np.random.rand(1,1000000)
b=np.random.rand(1,1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()
print(c)
print("Vectori"+str(1000*(toc-tic)))
  

ValueError: shapes (1,1000000) and (1,1000000) not aligned: 1000000 (dim 1) != 1 (dim 0)

In [7]:
a=np.random.rand(2,2)
print(a)

[[0.1140355  0.53590792]
 [0.95272867 0.99426301]]


In [17]:
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()
print(c)
print("Vectori"+str(1000*(toc-tic)))

249854.56906013726
Vectori8.008480072021484


In [23]:
a=np.array([[1],[3]])
print(a)
b=np.array([[1,3]])
print(b)

c=np.dot(a,b)
print(c)

[[1]
 [3]]
[[1 3]]
[[1 3]
 [3 9]]


In [26]:
import time
np.random.rand(3)
np.random.rand(3)

tic=time.time()
c=np.dot(a,b)
toc=time.time()
print(c)
print("Vectori"+str(1000*(toc-tic)))

0.684523886156287
Vectori0.0


In [4]:
import numpy as np
a=np.random.rand(1,1000000)
b=np.random.rand(1000000,1)
print(a)
print(b)
c=np.dot(a,b)
print(c)

[[0.65617183 0.06449639 0.01863607 ... 0.64816575 0.45678674 0.69014536]]
[[0.22346981]
 [0.82732426]
 [0.27367609]
 ...
 [0.54924315]
 [0.41305736]
 [0.47354646]]
[[250202.33890571]]


In [6]:
import numpy as np
v=np.random.rand(1000000)
u=np.exp(v)
print(v)

[0.52539248 0.39119487 0.33488274 ... 0.20878828 0.91514334 0.01921946]


In [11]:
import numpy as np
A=np.array([[1,2,3]])
print(A)

B=np.array([[1],[2],[3]])
print(B)
C=A*B
print(C)


[[1 2 3]]
[[1]
 [2]
 [3]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [12]:
import numpy as np
a=np.random.rand(5)


In [13]:
print(a)

[0.54145041 0.00227126 0.73366426 0.3911923  0.05650162]


In [14]:
print(a.shape)

(5,)


In [15]:
print(a.T)

[0.54145041 0.00227126 0.73366426 0.3911923  0.05650162]


In [16]:
print(a.T.shape)

(5,)


In [17]:
print(np.dot(a,a.T))

0.9876608013523624


In [18]:
a=np.random.rand(5,1)
print(a)

[[0.08153272]
 [0.6828005 ]
 [0.12435978]
 [0.15527564]
 [0.43283828]]


In [19]:
print(a.T)

[[0.08153272 0.6828005  0.12435978 0.15527564 0.43283828]]


a=np.random.rand(4,3)
b=np.random.rand(4,3)
c=a*b
print(c)
print(c.shape)


In [22]:
a=np.random.rand(4,3)
b=np.random.rand(4,3)
c=a*b
print(c)


[[0.1534862  0.00061322 0.24510821]
 [0.33983128 0.22037494 0.16442699]
 [0.0442591  0.38718347 0.18394102]
 [0.58639108 0.37432057 0.22762998]]


In [23]:
def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    import numpy as np
    s = 1/(1+np.exp(-x))
    ds = s(1-s)
    ### END CODE HERE ###
    
    return ds

In [24]:
x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

TypeError: 'numpy.ndarray' object is not callable

In [35]:

def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    x_norm = np.linalg.norm(x,axis=1,keepdims=True)
    
    # Divide x by its norm.
    x = np.dot(x,x_norm)
    ### END CODE HERE ###

    return x

In [37]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))


ValueError: shapes (2,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)

In [38]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print(image)

[[[0.67826139 0.29380381]
  [0.90714982 0.52835647]
  [0.4215251  0.45017551]]

 [[0.92814219 0.96677647]
  [0.85304703 0.52351845]
  [0.19981397 0.27417313]]

 [[0.60659855 0.00533165]
  [0.10820313 0.49978937]
  [0.34144279 0.94630077]]]


In [41]:
a=np.random.rand(4,2)
b=np.random.rand(2,4)
print(a)
print(b)
c=np.dot(a,b)
print(c)
print(c.shape)

[[0.6131744  0.3652761 ]
 [0.53158952 0.01802146]
 [0.09679493 0.56020905]
 [0.9407993  0.10021794]]
[[0.44953208 0.66516658 0.41095873 0.90531029]
 [0.78339114 0.50950422 0.9662981  0.68033537]]
[[0.56179562 0.59397283 0.60495497 0.80362334]
 [0.2530844  0.36277759 0.23587546 0.4935141 ]
 [0.48237523 0.34981363 0.58110766 0.46875948]
 [0.50142932 0.67684972 0.48347009 0.91989709]]
(4, 4)


In [3]:
import numpy as py
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print(gdot.shape)
print(len(x1))

dot = 278
 ----- Computation time = 0.0ms


NameError: name 'np' is not defined

In [5]:
import numpy as np
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print(dot.shape)

dot = 278
 ----- Computation time = 0.0ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.0ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.0ms


NameError: name 'W' is not defined

In [15]:
a=np.array([1,2])
print(a.shape)

b=np.array([[3,2,3],[2,3,3],[3,5,4]])
print(b)
print(a)
print(b.shape)
c=np.dot(b,a)
print(c)
print(c.shape)

(2,)
[[3 2 3]
 [2 3 3]
 [3 5 4]]
[1 2]
(3, 3)


ValueError: shapes (3,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage
from lr_utils import load_dataset

%matplotlib inline

ModuleNotFoundError: No module named 'h5py'

In [4]:
# Loading the data (cat/non-cat)
train_set_x_orig, train_set_y, test_set_x_orig, test_set_y, classes = load_dataset()

NameError: name 'load_dataset' is not defined

In [9]:
# GRADED FUNCTION: initialize_with_zeros

def initialize_with_zeros(dim):
    """
    This function creates a vector of zeros of shape (dim, 1) for w and initializes b to 0.
    
    Argument:
    dim -- size of the w vector we want (or number of parameters in this case)
    
    Returns:
    w -- initialized vector of shape (dim, 1)
    b -- initialized scalar (corresponds to the bias)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    w = np.zeros((dim,1))
    b = 0
    ### END CODE HERE ###

    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    
    return w, b

In [10]:
dim = 2
w, b = initialize_with_zeros(dim)
print ("w = " + str(w))
print ("b = " + str(b))
print(w.shape)


w = [[0.]
 [0.]]
b = 0
(2, 1)


In [12]:
a=np.array([1,2,3])
b=np.array([1,2,3])
c=a*b
print(c)

[1 4 9]


In [15]:
# GRADED FUNCTION: propagate

def propagate(w, b, X, Y):
    """
    Implement the cost function and its gradient for the propagation explained above

    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat) of size (1, number of examples)

    Return:
    cost -- negative log-likelihood cost for logistic regression
    dw -- gradient of the loss with respect to w, thus same shape as w
    db -- gradient of the loss with respect to b, thus same shape as b
    
    Tips:
    - Write your code step by step for the propagation. np.log(), np.dot()
    """
    
    m = X.shape[1]
    
    # FORWARD PROPAGATION (FROM X TO COST)
    ### START CODE HERE ### (≈ 2 lines of code)
    A = 1/(1+np.exp(-(np.dot(w.T,X)+b))                                      # compute activation
    cost = (-1/m)*(np.dot(Y,(np.log(A)).T)+(np.dot((1-Y),(np.log(1-A)).T)))                                  # compute cost
    ### END CODE HERE ###
    
    # BACKWARD PROPAGATION (TO FIND GRAD)
    ### START CODE HERE ### (≈ 2 lines of code)
    dw = None
    db = None
    ### END CODE HERE ###

    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

SyntaxError: invalid syntax (<ipython-input-15-61f5398a605d>, line 27)

In [14]:
w, b, X, Y = np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]])
grads, cost = propagate(w, b, X, Y)
print ("dw = " + str(grads["dw"]))
print ("db = " + str(grads["db"]))
print ("cost = " + str(cost))

AttributeError: 'NoneType' object has no attribute 'shape'

In [19]:
a=np.array([[1,2,3],[3,4,5]])
b=np.sum(a,axis=1)
print(b)
print(b.shape)
print(a.shape)

[ 6 12]
(2,)
(2, 3)
